name: flutter_onscreen_logger
description: "A Flutter package that allows you to display logs on the screen of your app for easier debugging."
version: 1.0.0
homepage: https://github.com/amm965/flutter_onscreen_logger
repository: https://github.com/amm965/flutter_onscreen_logger


environment:
  sdk: '>=3.2.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0

  get: ^4.6.6
  fluttertoast: ^8.2.8
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - lib/assets/

